// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://filasvejkaxxqonaemqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbGFzdmVqa2F4eHFvbmFlbXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDg5ODcsImV4cCI6MjA3MTQ4NDk4N30.tw_PEiql-tHRcZZlL5YKETn5BtEfctH2khZu8J78xX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});